/*
 * This code and all components (c) Copyright 2006 - 2025, Wowza Media Systems, LLC.  All rights reserved.
 * This code is licensed pursuant to the Wowza Public License version 1.0, available at www.wowza.com/legal.
 */

package com.wowza.wms.plugin.captions.whisper;

import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.wowza.util.StringUtils;
import com.wowza.wms.application.IApplicationInstance;
import com.wowza.wms.application.WMSProperties;
import com.wowza.wms.plugin.captions.audio.SpeechHandler;
import com.wowza.wms.plugin.captions.caption.Caption;
import com.wowza.wms.plugin.captions.caption.CaptionHandler;
import com.wowza.wms.plugin.captions.caption.CaptionHelper;
import com.wowza.wms.plugin.captions.metrics.MetricsRegistry;
import com.wowza.wms.plugin.captions.whisper.model.CaptionLine;
import com.wowza.wms.plugin.captions.whisper.model.WhisperResponse;
import com.wowza.wms.timedtext.model.ITimedTextConstants;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.Timer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;

import java.io.IOException;
import java.io.InputStream;
import java.net.Socket;
import java.net.SocketException;
import java.nio.ByteBuffer;
import java.time.Duration;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import java.util.stream.Collectors;

import static com.wowza.wms.plugin.captions.ModuleAzureSpeechToTextCaptions.PROP_DEFAULT_CAPTION_LANGUAGES;
import static com.wowza.wms.plugin.captions.ModuleCaptionsBase.*;
import static com.wowza.wms.plugin.captions.stream.DelayedStream.DEFAULT_START_DELAY;

public class WhisperSpeechToTextHandler implements SpeechHandler
{
    private static final Class<WhisperSpeechToTextHandler> CLASS = WhisperSpeechToTextHandler.class;
    private static final String CLASS_NAME = CLASS.getSimpleName();

    // MDC keys (must match what your Logback JSON encoder emits)
    private static final String MDC_SERVICE_NAME = "serviceName";
    private static final String MDC_SESSION_ID = "sessionId";
    private static final String MDC_REQUEST_ID = "requestId";

    private static final String SERVICE_NAME_VALUE = "wowza-captions";
    private static final String ENGINE_VALUE = "whisper";

    private static final Logger logger = LoggerFactory.getLogger(WhisperSpeechToTextHandler.class);
    private static final Timer STT_LATENCY_TIMER = Timer.builder("rttranslator_latency_seconds")
            .description("Latency between Whisper response and caption dispatch")
            .tag("engine", ENGINE_VALUE)
            .publishPercentileHistogram()
            .register(MetricsRegistry.registry());
    private static final Counter STT_ERRORS = Counter.builder("rttranslator_errors_total")
            .description("Total STT errors observed")
            .tag("engine", ENGINE_VALUE)
            .register(MetricsRegistry.registry());
    private static final Counter STT_DROPS = Counter.builder("rttranslator_drops_total")
            .description("Audio frames dropped because the socket was unavailable")
            .tag("engine", ENGINE_VALUE)
            .register(MetricsRegistry.registry());
    private static final Counter CAPTION_COUNTER = Counter.builder("rttranslator_captions_total")
            .description("Captions generated by Whisper")
            .tag("engine", ENGINE_VALUE)
            .register(MetricsRegistry.registry());

    private final LinkedBlockingQueue<ByteBuffer> audioBuffer = new LinkedBlockingQueue<>();
    private final Map<String, LinkedList<CaptionLine>> captionLines = new ConcurrentHashMap<>();

    private final CaptionHandler captionHandler;
    private Socket socket;
    private SocketListener socketListener;

    private final Map<String, String> languageMap;
    private final boolean debugLog;
    private final int maxLineLength;
    private final int maxLineCount;
    private final String socketHost;
    private final int socketPort;

    private final IApplicationInstance appInstance;
    private final int newLineThreshold;
    private final long delay;

    private volatile boolean doQuit = false;
    private volatile boolean outputRunning = false;

    private int retryCount = 0;

    // Trace fields for this handler lifetime
    private final String requestId = UUID.randomUUID().toString();

    public WhisperSpeechToTextHandler(IApplicationInstance appInstance, CaptionHandler captionHandler)
    {
        this.appInstance = appInstance;
        this.captionHandler = captionHandler;

        WMSProperties props = appInstance.getProperties();
        this.debugLog = props.getPropertyBoolean(PROP_CAPTIONS_DEBUG_LOG, false);
        this.maxLineLength = props.getPropertyInt(PROP_MAX_CAPTION_LINE_LENGTH, CaptionHelper.defaultMaxLineLengthSBCS);
        this.maxLineCount = props.getPropertyInt(PROP_MAX_CAPTION_LINE_COUNT, 2);
        this.newLineThreshold = props.getPropertyInt(PROP_NEW_LINE_THRESHOLD, DEFAULT_NEW_LINE_THRESHOLD);
        this.delay = props.getPropertyLong(PROP_CAPTIONS_STREAM_DELAY, DEFAULT_START_DELAY);

        String languagesStr = appInstance.getTimedTextProperties().getPropertyStr(
                PROP_DEFAULT_CAPTION_LANGUAGES,
                ITimedTextConstants.LANGUAGE_ID_ENGLISH
        );

        languageMap = Arrays.stream(languagesStr.split(","))
                .map(String::trim)
                .filter(s -> !s.isBlank())
                .collect(Collectors.toMap(
                        s -> toLocale(s).getLanguage(),
                        s -> s,
                        (existing, replacement) -> existing));

        this.socketHost = props.getPropertyStr("whisperSocketHost", "localhost");
        this.socketPort = props.getPropertyInt("whisperSocketPort", 3000);

        Gauge.builder("rttranslator_audio_buffer_depth", audioBuffer, LinkedBlockingQueue::size)
                .description("Pending audio frames waiting to be sent to Whisper")
                .tag("engine", ENGINE_VALUE)
                .tag("appInstance", appInstance.getContextStr())
                .register(MetricsRegistry.registry());

        // Minimal construction log (don’t leak sensitive config)
        logger.info("{} created (engine={} host={} port={} requestId={})",
                CLASS_NAME, ENGINE_VALUE, socketHost, socketPort, requestId);

        try
        {
            this.socket = new Socket(socketHost, socketPort);
            this.socketListener = new SocketListener();
            new Thread(socketListener, CLASS_NAME + ".SocketListener").start();
        }
        catch (IOException e)
        {
            socket = null;
            logger.error("{} error creating Whisper socket", CLASS_NAME, e);
        }
    }

    private void addExponentialDelayWithJitter()
    {
        long jitter = (long) (Math.random() * 1000); // up to 1 second jitter
        long baseDelay = 500;
        long sleepMs = baseDelay * (1L << retryCount) + jitter;

        try
        {
            Thread.sleep(sleepMs);
        }
        catch (InterruptedException ie)
        {
            Thread.currentThread().interrupt();
            throw new RuntimeException(ie);
        }
    }

    private void reconnect()
    {
        int maxRetries = 5;
        while (retryCount < maxRetries)
        {
            try
            {
                logger.info("pipeline event=stt_reconnect_attempt engine={} attempt={}/{} requestId={}",
                        ENGINE_VALUE, (retryCount + 1), maxRetries, requestId);

                if (socket != null && !socket.isClosed())
                {
                    socket.close();
                }

                socket = new Socket(socketHost, socketPort);
                socketListener = new SocketListener();
                new Thread(socketListener, CLASS_NAME + ".SocketListener").start();

                logger.info("pipeline event=stt_reconnect_success engine={} requestId={}", ENGINE_VALUE, requestId);
                return;
            }
            catch (Exception e)
            {
                socket = null;
                retryCount++;

                if (retryCount >= maxRetries)
                {
                    logger.error("pipeline event=stt_reconnect_fail engine={} attempts={} requestId={}",
                            ENGINE_VALUE, maxRetries, requestId, e);
                    return;
                }

                addExponentialDelayWithJitter();
            }
        }
    }

    @Override
    public void run()
    {
        // Add stable MDC values for this handler thread.
        // sessionId should ideally be set upstream in stream start/stop code.
        MDC.put(MDC_SERVICE_NAME, SERVICE_NAME_VALUE);
        MDC.put(MDC_REQUEST_ID, requestId);

        long startTs = System.currentTimeMillis();
        logger.info("pipeline event=stt_start engine={} requestId={}", ENGINE_VALUE, requestId);

        try
        {
            while (!doQuit)
            {
                try
                {
                    if (!outputRunning)
                    {
                        outputRunning = true;
                        appInstance.getVHost().getThreadPool().execute(this::processPendingCaptions);
                    }

                    ByteBuffer frame = audioBuffer.poll(100, TimeUnit.MILLISECONDS);
                    if (frame == null)
                        continue;

                    if (socket != null && socket.isConnected())
                    {
                        socket.getOutputStream().write(frame.array());
                        socket.getOutputStream().flush();
                    }
                    else
                    {
                        STT_DROPS.increment();
                        logger.warn("pipeline event=stt_socket_not_connected engine={} requestId={}", ENGINE_VALUE, requestId);
                        reconnect();
                    }
                }
                catch (Exception e)
                {
                    STT_ERRORS.increment();
                    if (doQuit)
                        break;

                    logger.warn("pipeline event=stt_runtime_error engine={} requestId={}", ENGINE_VALUE, requestId, e);
                    reconnect();

                    if (socket == null)
                    {
                        logger.error("pipeline event=stt_fail engine={} reason=socket_null requestId={}", ENGINE_VALUE, requestId);
                        break;
                    }
                }
            }

            long durationMs = System.currentTimeMillis() - startTs;
            logger.info("pipeline event=stt_success engine={} durationMs={} requestId={}", ENGINE_VALUE, durationMs, requestId);
        }
        catch (Exception e)
        {
            long durationMs = System.currentTimeMillis() - startTs;
            STT_ERRORS.increment();
            logger.error("pipeline event=stt_fail engine={} durationMs={} requestId={}", ENGINE_VALUE, durationMs, requestId, e);
        }
        finally
        {
            // Clear MDC for this handler thread
            MDC.remove(MDC_SESSION_ID);
            MDC.remove(MDC_REQUEST_ID);
            MDC.remove(MDC_SERVICE_NAME);
        }
    }

    private void processPendingCaptions()
    {
        try
        {
            List<Caption> captions = new ArrayList<>();

            for (Map.Entry<String, LinkedList<CaptionLine>> entry : captionLines.entrySet())
            {
                String language = entry.getKey();
                LinkedList<CaptionLine> lines = entry.getValue();

                synchronized (lines)
                {
                    Instant start = null;
                    Instant end = null;
                    List<String> textList = new ArrayList<>();
                    long earliestLineTimestamp = -1;

                    if (doQuit
                            || lines.size() > maxLineCount
                            || (!lines.isEmpty() && lines.peekLast().getTimeAdded() < System.currentTimeMillis() - delay / 2))
                    {
                        while (textList.size() < maxLineCount && !lines.isEmpty())
                        {
                            CaptionLine line = lines.removeFirst();
                            if (start == null)
                                start = line.getStart();
                            end = line.getEnd();
                            if (earliestLineTimestamp == -1)
                                earliestLineTimestamp = line.getTimeAdded();
                            textList.add(line.getText());
                        }
                    }

                    if (!textList.isEmpty())
                    {
                        // TODO: make trackid dynamic
                        Caption caption = new Caption(language, start, end, String.join("\n", textList), 99);
                        captions.add(caption);
                        recordLatency(earliestLineTimestamp);
                    }
                }
            }

            if (!captions.isEmpty())
            {
                CAPTION_COUNTER.increment(captions.size());
                logger.info("pipeline event=caption_generated engine={} count={}", ENGINE_VALUE, captions.size());
            }

            captions.forEach(captionHandler::handleCaption);

            if (!captions.isEmpty())
            {
                logger.info("pipeline event=caption_sent engine={} count={}", ENGINE_VALUE, captions.size());
            }
        }
        catch (Exception e)
        {
            logger.error("{}::processPendingCaptions error processing pending captions", CLASS_NAME, e);
        }
        finally
        {
            outputRunning = false;
        }
    }

    private void recordLatency(long earliestLineTimestamp)
    {
        if (earliestLineTimestamp <= 0)
        {
            return;
        }
        long latencyMs = System.currentTimeMillis() - earliestLineTimestamp;
        if (latencyMs < 0)
        {
            latencyMs = 0;
        }
        STT_LATENCY_TIMER.record(latencyMs, TimeUnit.MILLISECONDS);
    }

    @Override
    public void addAudioFrame(byte[] frame)
    {
        audioBuffer.add(ByteBuffer.wrap(frame));
    }

    @Override
    public void close()
    {
        logger.info("pipeline event=stt_close engine={} requestId={}", ENGINE_VALUE, requestId);

        if (socket != null)
        {
            try
            {
                socket.shutdownOutput();
            }
            catch (IOException e)
            {
                logger.error("{}::close error shutting down socket output", CLASS_NAME, e);
            }
        }
    }

    private void handleWhisperResponse(WhisperResponse response)
    {
        if (debugLog)
            logger.debug("whisper response received: {}", response);

        String language = languageMap.getOrDefault(response.getLanguage(), response.getLanguage());
        LinkedList<CaptionLine> lines = captionLines.computeIfAbsent(language, k -> new LinkedList<>());

        synchronized (lines)
        {
            String text = response.getText();
            if (StringUtils.isEmpty(text))
                return;

            Instant start = CaptionHelper.epochInstantFromMillis((long) (response.getStart() * 1000));
            Instant end = CaptionHelper.epochInstantFromMillis((long) (response.getEnd() * 1000));

            StringBuilder sb = new StringBuilder();
            CaptionLine line = lines.peekLast();

            if (line != null && Duration.between(line.getEnd(), start).toMillis() < newLineThreshold)
            {
                sb.append(line.getText());
            }
            else
            {
                line = new CaptionLine(language);
                line.setStart(start);
                lines.add(line);
            }

            List<String> items = Arrays.stream(text.split("\\s+")).toList();
            if (debugLog)
                logger.debug("whisper items: {}", items);

            float duration = response.getEnd() - response.getStart();
            float perWordDuration = items.isEmpty() ? 0 : duration / items.size();

            for (int i = 0; i < items.size(); i++)
            {
                String item = items.get(i);
                float itemStart = response.getStart() + (i * perWordDuration);
                float itemEnd = itemStart + perWordDuration;

                int length = sb.length();
                if (length > 0)
                {
                    // if next word would exceed max length, close line and start new one
                    if (length + 1 + item.length() > maxLineLength)
                    {
                        line.setEnd(end);
                        line.setText(sb.toString());
                        sb.setLength(0);

                        if (debugLog)
                            logger.debug("caption line committed: start={} end={} text={}", line.getStart(), line.getEnd(), line.getText());

                        line = new CaptionLine(language);
                        line.setStart(CaptionHelper.epochInstantFromMillis((long) (itemStart * 1000)));
                        lines.add(line);
                    }
                    else
                    {
                        sb.append(" ");
                    }
                }

                sb.append(item);
                end = CaptionHelper.epochInstantFromMillis((long) (itemEnd * 1000));
            }

            text = sb.toString();
            if (!text.isEmpty())
            {
                line.setEnd(end);
                line.setText(text);

                if (debugLog)
                    logger.debug("caption line updated: start={} end={} text={}", line.getStart(), line.getEnd(), line.getText());
            }
        }
    }

    private class SocketListener implements Runnable
    {
        @Override
        public void run()
        {
            try (InputStream inputStream = socket.getInputStream())
            {
                logger.info("pipeline event=stt_socket_listener_started engine={} requestId={}", ENGINE_VALUE, requestId);

                parseJsonStream(inputStream);

                doQuit = true;
                processPendingCaptions();

                logger.info("pipeline event=stt_socket_listener_stopped engine={} requestId={}", ENGINE_VALUE, requestId);
            }
            catch (SocketException s)
            {
                logger.info("{}::SocketListener SocketException: {}", CLASS_NAME, s.getMessage());
            }
            catch (IOException e)
            {
                logger.error("{}::SocketListener IOException", CLASS_NAME, e);
            }
            catch (Exception e)
            {
                logger.error("{}::SocketListener exception", CLASS_NAME, e);
            }
        }

        private void parseJsonStream(InputStream inputStream) throws IOException
        {
            JsonFactory factory = new JsonFactory();
            ObjectMapper objectMapper = new ObjectMapper();
            JsonParser parser = factory.createParser(inputStream);

            while (!parser.isClosed())
            {
                JsonToken token = parser.nextToken();
                if (token == JsonToken.START_OBJECT)
                {
                    WhisperResponse response = objectMapper.readValue(parser, WhisperResponse.class);
                    handleWhisperResponse(response);
                }
            }

            logger.info("{}.parseJsonStream: end", CLASS_NAME);
        }
    }
}