<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>nidaros-rtt-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFMpegCore" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NidarosRTT.Core\NidarosRTT.Core.csproj" />
    <ProjectReference Include="..\NidarosRTT.Infrastructure\NidarosRTT.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wwwroot\**\*;.env">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
